version: '3.8' 
services:
  mongo:
    image: mongodb/mongodb-community-server:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    command: ["mongod", "--auth", "--dbpath", "/data/db"]

volumes:
  mongo-data: